import type { MindmapNode } from "../core/types";

/**
 * Escapes XML special characters for safe XML/OPML/FreeMind serialization.
 */
export function escapeXml(str: string): string {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Exports a Mindmap tree as standard OPML 2.0 format.
 * Compatible with MindNode, OmniOutliner, XMind, Logseq, etc.
 */
export function exportMindmapToOpml(root: MindmapNode, docTitle?: string): string {
  const title = docTitle || root.text || "Knowledge Mindmap";
  const nowRfc822 = new Date().toUTCString();

  function serializeNode(node: MindmapNode, indentLevel: number): string {
    const indent = "  ".repeat(indentLevel);
    const escapedText = escapeXml(node.text || "分支主题");
    const escapedColor = node.color ? ` color="${escapeXml(node.color)}"` : "";

    if (!node.children || node.children.length === 0) {
      return `${indent}<outline text="${escapedText}"${escapedColor} />\n`;
    }

    let xml = `${indent}<outline text="${escapedText}"${escapedColor}>\n`;
    for (const child of node.children) {
      xml += serializeNode(child, indentLevel + 1);
    }
    xml += `${indent}</outline>\n`;
    return xml;
  }

  let bodyContent = "";
  // If root has children, root is the primary outline container
  bodyContent += serializeNode(root, 2);

  return `<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
  <head>
    <title>${escapeXml(title)}</title>
    <dateCreated>${nowRfc822}</dateCreated>
    <ownerName>KnowSpace</ownerName>
  </head>
  <body>
${bodyContent}  </body>
</opml>
`;
}

/**
 * Exports a Mindmap tree as standard FreeMind 1.0.1 (.mm) XML format.
 * Supported by XMind, FreeMind, Mindjet MindManager, Freeplane.
 */
export function exportMindmapToFreeMind(root: MindmapNode): string {
  let counter = 1;

  function serializeNode(node: MindmapNode, indentLevel: number): string {
    const indent = "  ".repeat(indentLevel);
    const id = `ID_${counter++}`;
    const escapedText = escapeXml(node.text || "主题");
    const colorAttr = node.color && node.color !== "transparent" ? ` COLOR="${escapeXml(node.color)}"` : "";
    const foldedAttr = node.collapsed ? ` FOLDED="true"` : "";

    if (!node.children || node.children.length === 0) {
      return `${indent}<node ID="${id}" TEXT="${escapedText}"${colorAttr}${foldedAttr} />\n`;
    }

    let xml = `${indent}<node ID="${id}" TEXT="${escapedText}"${colorAttr}${foldedAttr}>\n`;
    for (const child of node.children) {
      xml += serializeNode(child, indentLevel + 1);
    }
    xml += `${indent}</node>\n`;
    return xml;
  }

  return `<map version="1.0.1">
  <!-- Generated by KnowSpace Knowledge Mindmap Engine -->
${serializeNode(root, 1)}</map>
`;
}

/**
 * Exports a Mindmap tree as structured Markdown outline.
 */
export function exportMindmapToMarkdownOutline(root: MindmapNode): string {
  const lines: string[] = [];

  // Root heading
  lines.push(`# ${root.text || "知识导图"}\n`);

  function traverseChildren(children: MindmapNode[], indentLevel: number) {
    for (const node of children) {
      const indent = "  ".repeat(indentLevel);
      lines.push(`${indent}- ${node.text || "未命名主题"}`);
      if (node.children && node.children.length > 0) {
        traverseChildren(node.children, indentLevel + 1);
      }
    }
  }

  if (root.children && root.children.length > 0) {
    traverseChildren(root.children, 0);
  }

  return lines.join("\n") + "\n";
}
